### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by aksiksi** [saucewipe/pmppd#1]
Hey man! Long time no speak ;)

I've been loosely following your project and I think a short README would be helpful for people interested in what you're doing.

Also, is there any reason why you chose to go with C instead of C++11, Rust, Go, or even Java?

**Comment by saucewipe** [comment]
Hey Assil!

Yep. This is actually my graduation project. It's not public-ready yet.
We're slowly making it friendlier for outsiders to use, & the readme will
be updated.

As for the choice of language, C offers all the functionality we need
without extra bloat. All the Unix networking APIs we need are written in C
as well. I got this code to compile on both OS X & Linux.

Did you get the gist of it though?

--
Ali Razzouk

**Comment by aksiksi** [comment]
Oh awesome! It seems like a pretty cool project bro. I didn't really get a chance to dive through the code, but I at least get that it's a messaging protocol 😜

That makes sense. C is always good when you need low-level networking, but it's a pain to write secure and well-tested C in my opinion. Memory leaks are almost guaranteed to take place.

So you'll be graduating this semester? Are you planning on working or studying?

**Comment by saucewipe** [comment]
Oh there definitely are tons of memory leaks (I know that for a fact).

It's not exactly a "messaging" protocol in the chat sense. It's for helping
anyone set up their programs to easily use P2P networking rather than the
much-easier, traditional client-server.

I intend to work. Definitely had enough of academia.

--
Ali Razzouk

**Comment by aksiksi** [comment]
Haha, I like your honesty 👍 

I see. But doesn't the developer need to make changes to his/her software's architecture to accommodate a P2P networking system instead of client-server? I mean, it's difficult to design a drop-in replacement, or is that what you're aiming for?

Yeah, academia is tough. I'm actually going to start a PhD next semester. I really want to teach eventually and figured that the sooner I get it over with, the better.

**Comment by saucewipe** [comment]
I think you'd make a great teacher one day :)

That's exactly what I'm aiming for. It should be that simple to use P2P
networking. My belief is that P2P is the future. Obviously, other people
might come up with all sorts of imaginative ways to build services using
P2P that I never thought of if it becomes super easy for them to integrate.

--
Ali Razzouk
On Apr 19, 2016 4:16 PM, "Assil Ksiksi" <notifications@github.com> wrote:

Haha, I like your honesty 👍

I see. But doesn't the developer need to make changes to his/her software's
architecture to accommodate a P2P networking system instead of
client-server? I mean, it's difficult to design a drop-in replacement, or
is that what you're aiming for?

Yeah, academia is tough. I'm actually going to start a PhD next semester. I
really want to teach eventually and figured that the sooner I get it over
with, the better.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/saucewipe/pmppd/issues/1#issuecomment-211892549>

**Comment by aksiksi** [comment]
Thanks, I hope so haha!

Sounds awesome! And yeah, P2P has too many applications to count. I wish you the best of luck man :)
